# Generated by Django 4.2.8 on 2024-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_article_like_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(default=1, upload_to="products/images/"),
            preserve_default=False,
        ),
    ]
