# Generated by Django 4.2.8 on 2024-12-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="상품 이미지"
            ),
        ),
    ]
