# Generated by Django 4.2.8 on 2024-12-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_article_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="article_like_users",
        ),
        migrations.RemoveField(
            model_name="article",
            name="view_count",
        ),
    ]
