# Generated by Django 4.2.8 on 2024-12-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_remove_article_article_like_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="영화 이미지"
            ),
        ),
    ]
