# Generated by Django 4.2.8 on 2025-01-07 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0012_comment_comment_like_comment_writer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_like",
            field=models.ManyToManyField(
                blank=True, related_name="liked_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
