# Generated by Django 4.2.8 on 2025-01-08 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0013_alter_article_article_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_like",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
