# Generated by Django 4.2.8 on 2025-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_remove_article_title_article_article_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0, verbose_name="조회수"),
        ),
    ]
