# Generated by Django 4.2.8 on 2025-01-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0017_article_total_article_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="total_article_like",
            new_name="total_likes_count",
        ),
    ]
