# Generated by Django 4.2.8 on 2025-01-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0019_comment_total_commentlikes_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="articles.genre"
            ),
        ),
    ]
