# Generated by Django 4.2.8 on 2025-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0021_articlegenre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="genres",
        ),
        migrations.AddField(
            model_name="article",
            name="genre",
            field=models.CharField(
                choices=[
                    ("AC", "Action"),
                    ("DR", "Drama"),
                    ("CO", "Comedy"),
                    ("AD", "Adventure"),
                    ("AM", "Animation"),
                    ("CM", "Crime"),
                    ("DM", "Documentary"),
                    ("FT", "Fantasy"),
                    ("HO", "Horror"),
                    ("MC", "Musical"),
                    ("SF", "SF"),
                    ("RM", "Romance"),
                    ("MS", "Mystery"),
                    ("SP", "Sports"),
                    ("HR", "Hriller"),
                    ("WAR", "War"),
                ],
                default="AC",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ArticleGenre",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
