# Generated by Django 4.2.8 on 2025-01-24 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0024_remove_comment_total_commentlikes_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="total_commentlikes_count",
            field=models.IntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.AddField(
            model_name="comment",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
