# Generated by Django 4.2.8 on 2025-01-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0026_remove_comment_writer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="total_commentlikes_count",
        ),
    ]
