# Generated by Django 4.2.8 on 2024-12-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_follow_user_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="생일"),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=1, max_length=30, verbose_name="이름"),
            preserve_default=False,
        ),
    ]
