# Generated by Django 4.2.8 on 2025-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_article_article_like"),
        ("accounts", "0007_remove_user_birthdate_remove_user_introduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="article_likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="articles.article"
            ),
        ),
    ]
