# Generated by Django 4.2.8 on 2025-01-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0014_alter_comment_comment_like"),
        ("accounts", "0008_user_article_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comment_likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to="articles.comment"
            ),
        ),
    ]
